name: Manual Build Target

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Build Firmware
        run: |
          make TARGET=KAPONGA_KIWIF4_12S EXTRA_FLAGS="-Wno-error"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: betaflight-hex-file
          path: obj/*.hex
