name: Manual Build Target

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: betaflight/cloudbuild:v4.5
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Build Firmware
        run: |
          git config --global --add safe.directory '*'
          make TARGET=KAPONGA_KIWIF4_12S

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: betaflight-hex-file
          path: obj/*.hex
